-- Align the local schema with the app runtime data exported from the hosted project.
-- This intentionally does not recreate obsolete/source-analysis tables from the cloud dump.

create table if not exists public.course_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default now()
);

create table if not exists public.course_sub_categories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.course_categories(id) on delete cascade,
  name text not null,
  unique (category_id, name)
);

create table if not exists public.props (
  id text primary key,
  label text not null,
  icon text,
  color text,
  audio_cue text,
  banner_title text,
  banner_html text,
  created_at timestamp with time zone default now()
);

alter table public.course_categories enable row level security;
alter table public.course_sub_categories enable row level security;
alter table public.props enable row level security;

drop policy if exists "Public read access to course categories" on public.course_categories;
create policy "Public read access to course categories"
  on public.course_categories for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated users manage course categories" on public.course_categories;
create policy "Authenticated users manage course categories"
  on public.course_categories for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Public read access to course sub categories" on public.course_sub_categories;
create policy "Public read access to course sub categories"
  on public.course_sub_categories for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated users manage course sub categories" on public.course_sub_categories;
create policy "Authenticated users manage course sub categories"
  on public.course_sub_categories for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Public read access to props" on public.props;
create policy "Public read access to props"
  on public.props for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated users manage props" on public.props;
create policy "Authenticated users manage props"
  on public.props for all
  to authenticated
  using (true)
  with check (true);

alter table public.asana_categories
  add column if not exists color_code text,
  add column if not exists created_at timestamp with time zone default now();

alter table public.asanas
  add column if not exists category_legacy text,
  add column if not exists last_edited text,
  add column if not exists is_system boolean default true,
  add column if not exists stages text,
  add column if not exists recovery_pose_id text,
  add column if not exists preparatory_pose_id text,
  add column if not exists how_to_use_yoga_id text,
  add column if not exists yoga_the_iyengar_way_id text,
  add column if not exists devanagari text,
  add column if not exists translation text,
  add column if not exists oracle_lore text,
  add column if not exists symbol_prompt text,
  add column if not exists is_curated boolean default false,
  add column if not exists audio_url text,
  add column if not exists variation_code text,
  add column if not exists gem_plate text;

drop view if exists public.searchable_asanas_view;
drop view if exists public.view_asanas_admin;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'stages'
      and column_name = 'id'
      and data_type = 'uuid'
  ) then
    if exists (select 1 from public.stages limit 1) then
      raise exception 'Cannot convert public.stages.id from uuid to bigint because stages already has rows.';
    end if;

    alter table public.stages drop constraint if exists stages_pkey;
    alter table public.stages drop column id;
    alter table public.stages add column id bigint generated by default as identity primary key;
  end if;
end $$;

alter table public.stages
  alter column parent_id drop not null,
  alter column parent_id set default '{}'::text[],
  alter column recovery_pose_id type text using recovery_pose_id::text,
  add column if not exists plate_number text,
  add column if not exists hold_legacy text,
  add column if not exists preparatory_pose_id text,
  add column if not exists translation text,
  add column if not exists oracle_lore text,
  add column if not exists symbol_prompt text,
  add column if not exists is_curated boolean default false,
  add column if not exists audio_url text,
  add column if not exists audio_title text,
  add column if not exists sort_order integer,
  add column if not exists hold_json jsonb,
  add column if not exists intensity_override text,
  add column if not exists category_id_override bigint,
  add column if not exists is_restorative boolean default false,
  add column if not exists analysis_notes text;

alter table public.courses
  add column if not exists "sequence_text_ARCHIVED" text,
  add column if not exists last_edited timestamp with time zone,
  add column if not exists sub_category_id bigint,
  add column if not exists redirect_id bigint,
  add column if not exists is_alias boolean default false,
  add column if not exists condition_notes text;

alter table public.courses drop constraint if exists courses_title_category_key;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'courses_sub_category_id_fkey'
      and conrelid = 'public.courses'::regclass
  ) then
    alter table public.courses
      add constraint courses_sub_category_id_fkey
      foreign key (sub_category_id)
      references public.course_sub_categories(id)
      on delete set null;
  end if;
end $$;

alter table public.program_curriculum
  add column if not exists source_rule_id text,
  add column if not exists generated_from_rule boolean default false,
  add column if not exists is_optional boolean default false,
  add column if not exists mastery_gate_required boolean default false;

create or replace view public.view_asanas_admin as
select
  a.id,
  a.name,
  a.iast,
  a.english_name,
  a.technique,
  a.description,
  ac.name as category,
  a.category_id,
  a.gem_plate,
  a.plate_numbers,
  a.hold_json,
  a.page_primary,
  a.requires_sides,
  a.preparatory_pose_id,
  a.recovery_pose_id,
  a.audio_url,
  a.image_url,
  a.intensity,
  a.is_system,
  a.is_curated,
  null::uuid as user_id
from public.asanas a
left join public.asana_categories ac on ac.id = a.category_id;

grant select on public.view_asanas_admin to authenticated;

create or replace view public.searchable_asanas_view as
select
  a.id as source_id,
  a.id as asana_id,
  a.english_name as display_name,
  a.iast,
  a.name,
  ac.name as category,
  a.image_url,
  a.page_primary,
  null::text as stage_name,
  null::text as stage_title,
  null::text as stage_shorthand,
  'asana' as source_type
from public.asanas a
left join public.asana_categories ac on ac.id = a.category_id

union all

select
  s.id::text as source_id,
  s.asana_id as asana_id,
  coalesce(s.title, a.english_name) as display_name,
  s.devanagari as iast,
  coalesce(s.title, a.name) as name,
  ac.name as category,
  coalesce(s.image_url, a.image_url) as image_url,
  s.page_primary,
  s.stage_name,
  s.title as stage_title,
  s.shorthand as stage_shorthand,
  'stage' as source_type
from public.stages s
left join public.asanas a on a.id = s.asana_id
left join public.asana_categories ac on ac.id = a.category_id;

grant select on public.searchable_asanas_view to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('yoga-cards', 'yoga-cards', true, 52428800, array['image/webp', 'image/png', 'image/jpeg']::text[]),
  ('audio-assets', 'audio-assets', true, 52428800, array['audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/ogg', 'audio/mp4']::text[])
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read access to yoga cards" on storage.objects;
create policy "Public read access to yoga cards"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'yoga-cards');

drop policy if exists "Public read access to audio assets" on storage.objects;
create policy "Public read access to audio assets"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'audio-assets');
